include:
  - project: 'studi.devops/gitlab-cicd-templates'
    ref: master
    file: 'versioning/default.gitlab-ci.yml'

  - project: 'studi.devops/gitlab-cicd-templates'
    ref: master
    file: 'build/dotnet/linux/default.gitlab-ci.yml'

  - project: 'studi.devops/gitlab-cicd-templates'
    ref: master
    file: 'deploy/app/default.gitlab-cd.yml'
  
build project Studi.Api.Proctoring:
  extends: .build dotnet
  variables:    
    project_name: 'Studi.Api.Proctoring'
    project_path: 'src/Studi.Api.Proctoring/Studi.Api.Proctoring.csproj'